[tox]
requires =
    tox>=4.22
    tox-uv>=1.25
envlist = py{310,311,312,313}
skip_missing_interpreters = True

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    dev
uv_python_preference = only-managed
allowlist_externals =
    uv
    poe
commands =
    poe check
    poe test
    poe build
